### ISSUE TITLE
Is there a way to limit build artifacts being deployed with  --exclude?

### ISSUE THREAD

**Issue by slothluvchunk** [pantheon-systems/terminus-rsync-plugin#15]
When using this inside of a CI process, there will often be the need to exclude folders like `.git` or `/vendor`, etc. 
I've noticed in the src that there is a hardcoded `--exclude .git/` passed along with RsyncOptions, but can't seem to use the --exclude argument in the rsync command itself. 
It would be great to be able to do something like: 
`terminus rsync site.env ./build_directory/ /pantheon:code/directory/ --exclude .git/ --exclude node_modules/` or similar. 
Is this available and I'm just missing it, or is this something that can be added?

**Comment by greg-1-anderson** [comment]
Add `--` to your command line. Everything that comes after the `--` will be ignored by Terminus and will be passed on to Rsync, so you can add extra `--exclude` options there.

**Comment by slothluvchunk** [comment]
Perfect - thanks @greg-1-anderson.
