### ISSUE TITLE
terminus-rsync-plugin not compatible with Terminus 2.4.0 version

### ISSUE THREAD

**Issue by jenlampton** [pantheon-systems/terminus-rsync-plugin#17]
I just updated to the latest version of terminus, and every time I run a command I'm now presented with the following:

```
 [warning] Could not load plugin pantheon-systems/terminus-rsync-plugin because it is not compatible with this version of Terminus.
```

I have tried deleting the plugin and reinstalling it (as per [the documentation](https://pantheon.io/docs/terminus/plugins)) to no avail.

**Comment by greg-1-anderson** [comment]
Are you installing from the 1.x branch? That should be compatible with Terminus 2

**Comment by greg-1-anderson** [comment]
Try https://github.com/pantheon-systems/terminus-rsync-plugin/tree/1.1.0#installation

**Comment by jenlampton** [comment]
> Are you installing from the 1.x branch? 

Yes, I downloaded the 1.0.1 release manually as per https://pantheon.io/docs/terminus/plugins

> Try 1.1.0#installation

This worked!

`composer create-project --no-dev -d ~/.terminus/plugins pantheon-systems/terminus-rsync-plugin:~1`

Thank you :)
