### ISSUE TITLE
rsync doesn't show in `terminus list`

### ISSUE THREAD

**Issue by ElijahLynn** [pantheon-systems/terminus-rsync-plugin#8]
After installing terminus-rsync-plugin, a `terminus list` doesn't show it as a command. Maybe this needs to go into terminus core?

**Comment by greg-1-anderson** [comment]
`rsync` is the command alias; the primary command name is `remote:rsync`. Look for a line that looks like this:
```
  remote:rsync               [rsync] Call rsync on a Pantheon site
```

**Comment by ElijahLynn** [comment]
Ahh, thank you, I did see that but thought that was a different command.
