### ISSUE TITLE
Software caused connection abort (103)

### ISSUE THREAD

**Issue by stephencapellic** [pantheon-systems/terminus-rsync-plugin#9]
After a long wait (can't see progress so not sure what is happening) and many of my files transferring, I eventually get flood with errors:

Here’s a short list, but there are about x20 more lines:

rsync: failed to open “/srv/bindings/931a4ab378b94b68bce6558f5e1da1ef/files/images/featured-product/Ger_Family2_0.jpg”, continuing: Software caused connection abort (103)
rsync: recv_generator: failed to stat “/srv/bindings/931a4ab378b94b68bce6558f5e1da1ef/files/images/featured-product/Goat.jpg”: Transport endpoint is not connected (107)
rsync: recv_generator: failed to stat “/srv/bindings/931a4ab378b94b68bce6558f5e1da1ef/files/images/featured-product/Goat_0.jpg”: Transport endpoint is not connected (107)
rsync: recv_generator: failed to stat “/srv/bindings/931a4ab378b94b68bce6558f5e1da1ef/files/images/featured-product/Goat_1.jpg”: Transport endpoint is not connected (107)
rsync: recv_generator: failed to stat “/srv/bindings/931a4ab378b94b68bce6558f5e1da1ef/files/images/featured-product/Goat_2.jpg”: Transport endpoint is not connected (107)

Finally it fails with an error 23.

**Comment by greg-1-anderson** [comment]
Perhaps you hit the 60-minute hard timeout. See https://pantheon.io/docs/timeouts/

You could try running the rsync again. In theory, if some files were transferred successfully, the rsync will get farther on the second run, as it should take comparatively little time to skip past the progress from last time.
